### PR TITLE
Https everywhere

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
Could you please review @diracdeltas?

### CODE REVIEW

**Comment by diracdeltas** [comment]
lgtm at a glance, though i don't android/java. simple test cases:
* http://apple.com should go to HTTPS
* http://nikeplus.com should NOT go to https://secure-nikeplus.nike.com/, otherwise an exclusion is being ignored.

**Comment by SergeyZhukovsky** [comment]
#1 is true for me
#2 is false
Are you sure there is an exclusion for http://nikeplus.com?
I have that ruleset on it:
{"ruleset":{"$":{"name":"Nike.com (partial)","f":"Nike.com.xml","default_off":"breaks nikeplus.com"},"securecookie":[{"$":{"host":"^\\.nike\\.com$","name":"^(?:AnalysisUserId|ResonanceSegment|RES_TRACKINGID|s_\\w+|utag_main)$"}},{"$":{"host":"^(?:help-[\\w-]+|secure-store)\\.nike\\.com$","name":".+"}}],"rule":[{"$":{"from":"^http://nike\\.com/","to":"https://www.nike.com/"}},{"$":{"from":"^http://images\\.nike\\.com/","to":"https://a248.e.akamai.net/f/471/3529/6d/images.nike.com/"}},{"$":{"from":"^http://modus\\.nike\\.com/","to":"https://nike-com.112.2o7.net/"}},{"$":{"from":"^http://nikeplus\\.nike\\.com/","to":"https://secure-nikeplus.nike.com/"}},{"$":{"from":"^http://store\\.nike\\.com/","to":"https://secure-store.nike.com/"}},{"$":{"from":"^http://ugc\\.nike\\.com/","to":"https://a248.e.akamai.net/f/259/7435/9m/ugc.nike.com/"}},{"$":{"from":"^http:","to":"https:"}}]}}


Also verified it on laptop browser and it goes to https://secure-nikeplus.nike.com/

**Comment by diracdeltas** [comment]
Sorry by "exclusion" i meant "default off or exclusion" :). That ruleset is correct, it has the "default_off" attribute so shouldn't be applied. On laptop-browser, nikeplus.com correctly redirects to https://secure-nikeplus.nike.com/plus/ (not  https://secure-nikeplus.nike.com/) for me

**Comment by SergeyZhukovsky** [comment]
Ya, sorry also :). nikeplus.com redirects itself to https://secure-nikeplus.nike.com/plus/mobile for me also. And ya the logic skips it as found default_off.

Seems like 2 test cases are correct.

**Comment by SergeyZhukovsky** [comment]
Could I merge that @diracdeltas?. I want to make a release today with that feature.

**Comment by diracdeltas** [comment]
yep!

**Comment by bbondy** [comment]
yay can't wait to tweet about this :+1:

**Pull request merged**
